CityGuide/Backup/ViewModels/CategoryViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CityGuide.ViewModels
{
    public class CategoryViewModel
    {
        public string Name { get; set; }
        public int Id { get; set; }
    }
}

CityGuide/Backup/ViewModels/ObjectiveViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using CG.Domain;

namespace CityGuide.ViewModels
{
    public class ObjectiveViewModel
    {
        public string Name { get; set; }
        public int Id { get; set; }
        public int Score { get; set; }
        public int Category { get; set; }
        public string Description { get; set; }
        public virtual List<Photo> Photos { get; set; }
        public virtual List<Review> Reviews { get; set; }
    }
}

CityGuide/Backup/ViewModels/PhotoViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CityGuide.ViewModels
{
    public class PhotoViewModel
    {
        public int Id;
        public string Url;
    }
}

CityGuide/Backup/ViewModels/ReviewViewModel.cs
namespace CityGuide.ViewModels
{
    public class ReviewViewModel
    {
        public int Id { get; set; }
        public int IdUser { get; set; }
        public int ReviewScore { get; set; }
        public int ScoreGiven { get; set; }
        public string Text { get; set; }
    }
}

CityGuide/Backup/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CG.DataAccess;
using CG.Domain;
using CityGuide.Application;

namespace CityGuide.Controllers
{
    public class CategoryController : Controller
    {
        private CityGuideContext db = new CityGuideContext();
        private ObjectivesWorkerService _objWorkerSvc;

        public CategoryController(ObjectivesWorkerService objService)
        {
            _objWorkerSvc = objService;
        }

        public ActionResult Details(int? id, string searchString, string sortOrder = "")
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Category category = db.Categories.Find(id);

            if (category == null)
            {
                return HttpNotFound();
            }

            if (!String.IsNullOrEmpty(searchString))
            {
                ViewBag.Objectives = _objWorkerSvc.GetObjectivesFromSearch(id.Value, searchString, sortOrder);
            }
            else
                ViewBag.Objectives = _objWorkerSvc.GetObjectivesFromCategory(id.Value, sortOrder);

            ViewBag.test = _objWorkerSvc.testFunction();

            return View(category);
        }
        
    }
}

CityGuide/Backup/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CityGuide.Application;

namespace CityGuide.Controllers
{
    public class HomeController : Controller
    {
        private CategoriesWorkerService _catWorkerSvc;

        public HomeController(CategoriesWorkerService catService)
        {
            _catWorkerSvc = catService;
        }

        public ActionResult Index()
        {
            var viewModels = _catWorkerSvc.GetAllCategories();
            return View(viewModels);
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

CityGuide/Backup/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CityGuide.Controllers
{
    public class LoginController : Controller
    {
        // GET: Login
        public ActionResult Index()
        {
            return View();
        }
    }
}

CityGuide/Backup/Controllers/ObjectiveController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CG.DataAccess;
using CG.Domain;

namespace CityGuide.Controllers
{
    public class ObjectiveController : Controller
    {
        private CityGuideContext db = new CityGuideContext();
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Objective objective = db.Objectives.Find(id);
            if (objective == null)
            {
                return HttpNotFound();
            }
            return View(objective);
       }
    }
}

CityGuide/Backup/Views/Category/Create.cshtml
@model CG.Domain.Category

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Category</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CityGuide/Backup/Views/Category/Delete.cshtml
@model CG.Domain.Category

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Category</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

CityGuide/Backup/Views/Category/Details.cshtml
@model CG.Domain.Category

@{
    ViewBag.Title = Html.DisplayFor(model => model.Name);
}

<h3>@Html.DisplayFor(model => model.Name)</h3>

<hr />
@using (Html.BeginForm())
{
    <p>
        Title: @Html.TextBox("searchString")
        <input type="submit" value="Filter" />
    </p>
}

@using (Html.BeginForm())
{
    <p>
        Sort by:
        <select id="sortOrder" name="sortOrder">
            <option value="">Name</option>
            <option value="name_desc">Name descending</option>
            <option value="score">Score</option>
            <option value="score_desc">Score descending</option>
        </select>
        <input type="submit" />
        
    </p>
}
 
<div>
    @foreach (var o in ViewBag.Objectives)
    {
        <div class="objective-square" style="background: url(@o.Photos[0].Url)  no-repeat center center; background-size:cover">
            @Html.ActionLink((string)o.Name, "Details/" + (int)@o.Id, "Objective")
            </div>
    }

    <div style="clear:both"></div>
</div>

CityGuide/Backup/Views/Category/Edit.cshtml
@model CG.Domain.Category

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Category</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CityGuide/Backup/Views/Category/Index.cshtml
@model IEnumerable<CG.Domain.Category>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

CityGuide/Backup/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

CityGuide/Backup/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

CityGuide/Backup/Views/Home/Index.cshtml
@model List<CityGuide.ViewModels.CategoryViewModel>
@{
    ViewBag.Title = "Home Page";
}

<div class="main">
    @foreach (var cat in Model)
    {
        <div class="category-square">@Html.ActionLink(@cat.Name, "Details/" + @cat.Id, "Category")</div>
    }
    <div style="clear: both"></div>
</div>

CityGuide/Backup/Views/Login/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

CityGuide/Backup/Views/Objective/Create.cshtml
@model CG.Domain.Objective

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Objective</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Score, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Score, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Score, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Category, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Category, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Category, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CityGuide/Backup/Views/Objective/Delete.cshtml
@model CG.Domain.Objective

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Objective</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Score)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Score)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Category)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

CityGuide/Backup/Views/Objective/Details.cshtml
@model CG.Domain.Objective

@{
    ViewBag.Title = "Details";
}
<div style="padding:2%">
    <h2>@Html.DisplayFor(model => model.Name) <span class="glyphicon glyphicon-star-empty" aria-hidden="true" style="float:right;"></span></h2>
    <input id="input-7-xs" class="rating rating-loading" value="1" data-min="0" data-max="5" data-step="1" data-size="xs"><hr />
    <div>
        <div class="swiper-container">
            <div class="swiper-wrapper">
                @foreach (var i in Model.Photos)
                {
                    <div class="swiper-slide" style="background-image:url(@i.Url)"></div>
                }
            </div>
        </div>
    </div>
    <hr />
    <p>Read reviews</p>
    <hr />
    @Html.DisplayFor(model => model.Description)
    <hr />
    <script src="../../Content/dist/js/swiper.min.js" type="text/javascript"></script>
    <script src="../../Content/dist/js/star-rating.js" type="text/javascript"></script>
    <!-- Initialize Swiper -->
    <script>
        var swiper = new Swiper('.swiper-container');
        $(document).ready(function() {
            $("#input-id").rating()
        });
    </script>
</div>

CityGuide/Backup/Views/Objective/Edit.cshtml
@model CG.Domain.Objective

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Objective</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Score, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Score, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Score, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Category, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Category, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Category, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CityGuide/Backup/Views/Objective/Index.cshtml
@model IEnumerable<CG.Domain.Objective>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Score)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Category)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Score)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Category)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

CityGuide/Backup/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Cluj-Napoca City Guide</title>
    <link href="http://netdna.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.css" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link rel="stylesheet" href="../../Content/dist/css/swiper.min.css">
    <link rel="stylesheet" href="../../Content/dist/css/star-rating.css">
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <!--Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { class = "navbar-brand" })-->
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse" style="float:right !important;"><span class="glyphicon glyphicon-user white"></span></button>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Login", "Index", "Login")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
</div>
    </div>
    <div class="">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>